#!/bin/python3

# compare first argument and stdin

import sys
from itertools import zip_longest as zip

s = input()
failed = False

for index, (i, j) in enumerate(zip(s, sys.argv[1])):
    failed = failed or i != j

if failed:
    print(f'failed\nexpected:\t"{sys.argv[1]}"\ngot:\t\t"{s}"', file=sys.stderr)
